package com.aefyr.pseudoapksigner;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.Signature;
import java.security.interfaces.RSAPrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.zip.CRC32;
import java.util.zip.Deflater;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

/**
 * Vendored, clean-room reimplementation of Aefyr/PseudoApkSigner
 * (https://github.com/Aefyr/PseudoApkSigner, Apache 2.0), kept at the
 * original package name so callers need no changes.
 * <p>
 * Why this exists: the original library was only ever published to JCenter
 * (dead since 2022) and JitPack, and its own build no longer resolves on
 * current JitPack infrastructure - {@code com.github.aefyr:pseudoapksigner:1.6}
 * fails dependency resolution entirely.
 * <p>
 * Signs an APK by re-computing per-entry SHA1 digests into a fresh
 * MANIFEST.MF, wrapping that in a .SF signature file, and pairing it with a
 * pre-existing .RSA "template" (here named .past) whose trailing signature
 * block bytes get replaced with a real signature produced from the given
 * private key. This only works if the template file was originally
 * generated by signing something with the *same* private key via a real
 * signing tool - which is exactly how the bundled testkey.past/testkey.pk8
 * assets were produced.
 */
public class PseudoApkSigner {

    private static final String HASH_ALGORITHM = "SHA1";
    private static final String[] META_INF_SKIP_SUFFIXES = {"manifest.mf", ".sf", ".rsa", ".dsa", ".ec"};

    private final File templateFile;
    private final RSAPrivateKey privateKey;
    private String signerName = "CERT";

    public PseudoApkSigner(File templateFile, File privateKeyFile) throws GeneralSecurityException, IOException {
        this.templateFile = templateFile;
        this.privateKey = readPrivateKey(privateKeyFile);
    }

    public void setSignerName(String signerName) {
        this.signerName = signerName;
    }

    public void sign(File apkFile, File output) throws IOException, GeneralSecurityException {
        try (InputStream input = new FileInputStream(apkFile);
             OutputStream out = new FileOutputStream(output)) {
            sign(input, out);
        }
    }

    public void sign(InputStream apkInputStream, OutputStream output) throws IOException, GeneralSecurityException {
        Map<String, String> manifestEntries = new LinkedHashMap<>();
        ZipInputStream zipIn = new ZipInputStream(apkInputStream);
        ZipOutputStream zipOut = new ZipOutputStream(output);
        zipOut.setLevel(Deflater.BEST_COMPRESSION);

        MessageDigest digest = MessageDigest.getInstance(HASH_ALGORITHM);

        ZipEntry entry;
        entryLoop:
        while ((entry = zipIn.getNextEntry()) != null) {
            if (entry.isDirectory())
                continue;

            String lowerName = entry.getName().toLowerCase();
            if (lowerName.startsWith("meta-inf/")) {
                for (String skip : META_INF_SKIP_SUFFIXES) {
                    if (lowerName.endsWith(skip))
                        continue entryLoop;
                }
            }

            byte[] bytes = readAllBytes(zipIn);
            digest.reset();

            ZipEntry newEntry = new ZipEntry(entry.getName());
            if (entry.getMethod() == ZipEntry.STORED) {
                newEntry.setMethod(ZipEntry.STORED);
                newEntry.setSize(bytes.length);
                newEntry.setCompressedSize(bytes.length);
                CRC32 crc = new CRC32();
                crc.update(bytes);
                newEntry.setCrc(crc.getValue());
            }

            zipOut.putNextEntry(newEntry);
            zipOut.write(bytes);
            zipOut.closeEntry();
            zipIn.closeEntry();

            manifestEntries.put(entry.getName(), base64(digest.digest(bytes)));
        }
        zipIn.close();

        String manifest = buildManifest(manifestEntries);
        zipOut.putNextEntry(new ZipEntry("META-INF/MANIFEST.MF"));
        zipOut.write(manifest.getBytes(StandardCharsets.UTF_8));
        zipOut.closeEntry();

        String signatureFile = buildSignatureFile(manifest);
        zipOut.putNextEntry(new ZipEntry("META-INF/" + signerName + ".SF"));
        zipOut.write(signatureFile.getBytes(StandardCharsets.UTF_8));
        zipOut.closeEntry();

        zipOut.putNextEntry(new ZipEntry("META-INF/" + signerName + ".RSA"));
        zipOut.write(readAllBytesFromFile(templateFile));
        zipOut.write(sign(signatureFile.getBytes(StandardCharsets.UTF_8)));
        zipOut.closeEntry();

        zipOut.close();
    }

    private byte[] sign(byte[] data) throws GeneralSecurityException {
        Signature signature = Signature.getInstance("SHA1withRSA");
        signature.initSign(privateKey);
        signature.update(data);
        return signature.sign();
    }

    private String buildManifest(Map<String, String> entries) {
        StringBuilder sb = new StringBuilder();
        sb.append("Manifest-Version: 1.0\r\n\r\n");
        for (Map.Entry<String, String> e : entries.entrySet()) {
            sb.append("Name: ").append(e.getKey()).append("\r\n");
            sb.append(HASH_ALGORITHM).append("-Digest: ").append(e.getValue()).append("\r\n\r\n");
        }
        return sb.toString();
    }

    private String buildSignatureFile(String manifest) throws GeneralSecurityException {
        byte[] wholeFileDigest = MessageDigest.getInstance(HASH_ALGORITHM)
                .digest(manifest.getBytes(StandardCharsets.UTF_8));
        String sb = "Signature-Version: 1.0\r\n" +
                HASH_ALGORITHM + "-Digest-Manifest: " + base64(wholeFileDigest) + "\r\n\r\n";
        return sb;
    }

    private static String base64(byte[] bytes) {
        return Base64.getEncoder().encodeToString(bytes);
    }

    private static RSAPrivateKey readPrivateKey(File file) throws GeneralSecurityException, IOException {
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(readAllBytesFromFile(file));
        return (RSAPrivateKey) KeyFactory.getInstance("RSA").generatePrivate(keySpec);
    }

    private static byte[] readAllBytesFromFile(File file) throws IOException {
        try (InputStream in = new FileInputStream(file)) {
            return readAllBytes(in);
        }
    }

    private static byte[] readAllBytes(InputStream in) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] chunk = new byte[8192];
        int read;
        while ((read = in.read(chunk)) != -1) {
            buffer.write(chunk, 0, read);
        }
        return buffer.toByteArray();
    }
}
